### ISSUE TITLE
Switches stop responding from home assistant after a couple of hours

### ISSUE THREAD

**Issue by panagiotis55** [CoolKit-Technologies/ha-addon#59]
The switches stop responding from home assistant after a couple of hours. Also automations stop working too and the core logs give me these errors:
WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.a4800210d1
even when the switches still work.
I'm on 1.2.3
The problem is only temporarily resolved after a host reboot.

**Comment by drusha** [comment]
I confirm this behavior on eWeLink addon version 1.2.3 and Home Assistant OS version 2021.12.8. Cloud only, no LAN mode.

My temporary sort-of-workaround was to create a badge that links to a script that restarts eWeLink Smart Home addon. Unfortunately, I don't know how to automate detection of the addon crash and I run the script manually every time when eWeLink devices become unresponsive.

**Comment by drusha** [comment]
After recent EWeLink EU server outage couple of days ago the problem seems to be resolved. Apparently it was an overloaded cloud. But still, the add-on should probably handle server outages a little better.

**Comment by TamasHodi** [comment]
I think it is not related to the outage because this issue keeps happening a long time (3 months at least) ago and still persists (appeared again yesterday and got broken within 12 hours).

The mobile app (eWeLink) shows the proper sensor states while the HA add-on keeps running without receiving any events or updates.
The state can be forced to be synced by pushing `sync` button within the web interface but that's a one-time solution only, I have to restart the whole add-on in order to fix it as https://github.com/CoolKit-Technologies/ha-addon/issues/59#issuecomment-1008172051 mentioned.

I could find no traces within the logs which could explain the broken state sync and I have no clue how to reproduce the bug.

My current setup:
- HA OS @ 7.1
- HA-addon @ 1.2.3
- SONOFF ZBBridge 3.0 @ 1.4.1

I'm considering leaving the platform because of this instability by swapping out the bee hub to have something working via LAN.
Any suggestions are welcome!

**Comment by niezw** [comment]
Please use the latest version, we have made some updates

If you still have this problem, please reopen the issue.
If there are other problems, please create a new issue.
